(define display write)
(define len length)
(define (nil) "nil obj" ())
(define (ok) "ok obj" ())
(define fold foldl)
(define reduce fold)
(define ceil ceiling)
(define head car)
(define tail list-tail)
